[features]
seeds = false
skip-lint = false
[programs.localnet]
example1 = "7MvdKbxE1XiuayNVFZFsmGXn2Z4Afb38XQuMC2hbVAMc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ogami/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
